name: Deploy to AWS

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: 'us-east-1'
  TF_STATE_BUCKET: 'dynamic-website-tf-state-2024'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Create Lambda packages
      run: |
        cd lambda
        pip install -r requirements.txt -t .
        zip -r get_string.zip .
        cp get_string.zip update_string.zip
        # Note: Both functions share the same dependencies
        # so we can use the same package

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
