name: Destroy Infrastructure

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    # Optional: Auto-destroy nightly to save costs (adjust as needed)
    - cron: '0 2 * * *'  # 2 AM UTC daily

env:
  AWS_REGION: 'us-east-1'

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only allow from main branch

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.0'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false
